spring.application.name=auth
#==================================
server.address=0.0.0.0
server.port=8082

spring.datasource.url=jdbc:postgresql://ep-rough-haze-a18iashw-pooler.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require&prepareThreshold=0
spring.datasource.username=neondb_owner
spring.datasource.password=npg_vWzZQdJ82Ppt
spring.jpa.properties.hibernate.default_schema=spacezentauth

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.expiration=86400

superadmin.email=superadmin@gmail.com
superadmin.password=superadmin


dev.otp.enabled=true
dev.otp.phone=9999999999
dev.otp.code=123456